### ISSUE TITLE
sodium-native as an optional dependency?

### ISSUE THREAD

**Issue by aral** [emilbayes/secure-random-uniform#3]
Hey Emil, hope you’re well. Would you be open to a pull request that makes sodium-native an optional/peer dependency?

I’m currently using your excellent eff-diceware-passphrase module which depends on this module which, in turn, depends on sodium-native. It’s the only native dependency in my project and is currently blocking me from bundling it into a single file for deployment (I’m trying to get deployments of my small web server as quick as possible). 

As for the implementation, I was thinking of one that would use sodium-native as a peer dependency if installed but default to libsodium-wrappers (unless you’d have a different way of handling it that you’d prefer).

I realise this is probably a niche use case, so please feel free to say no :)

**Comment by aral** [comment]
Just looking at the code, it seems the only place sodium-native is used is in `sodium.randombytes_buf(buf)`. Could we not use the built-in crypto module here instead? (I might be missing something.)

**Comment by aral** [comment]
Scratch that, wouldn’t work in the browser (of course). Right, so maybe something smaller like tweetnacl?

**Comment by aral** [comment]
Closing as I’m making a very lightweight fork of your lovely EFF package and inlining the functions instead. Thanks again for all your awesome work :)

**Comment by aral** [comment]
PS. Here it is: https://github.com/small-tech/eff-diceware-passphrase – thank you again. I ended up making it a dependency-free single file with a class that you pass a reference to the standard Node crypto library when using it under Node.js and where it auto-detects the browser and uses the Web Crypto API (the only crypto function being used was random bytes so it wasn’t hard to get it working) :)

**Comment by emilbayes** [comment]
Hi! This should be very easy to make work in the browser with sodium-universal and quite small too with the new structure we have in that module. Happy to change it if you still have a need :)

**Comment by aral** [comment]
@emilbayes Hey Emil, thanks so much, man. I just hacked this together last night so I’m sorted: https://github.com/small-tech/eff-diceware-passphrase/blob/main/index.js

So please don’t spend time on this just for me. Appreciate it, though + love you work :)
